{% set name = "file" %}
{% set version = "5.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ftp://ftp.astron.com/pub/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f05d286a76d9556243d0cb05814929c2ecf3a5ba07963f8f70bfaaa70517fad1

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - zlib  # [unix]

test:
  commands:
    - file -v
    - file --version  # same as above
    - file --help

outputs:
  - name: libmagic
    files:
      - include/
      - lib/
      - share/misc/

  - name: file
    requirements:
      run:
        - {{ pin_compatible("libmagic", max_pin="x.x.x.x.x.x.x.x.x") }}
    files:
      - bin/
      - share/man/

about:
  home: http://darwinsys.com/file
  license: BSD-2-clause
  license_family: BSD
  license_file: COPYING
  summary: Fine Free File Command
  description: |
    The file command is "a file type guesser", that is, a command-line tool
    that tells you in words what kind of data a file contains. Unlike most GUI
    systems, command-line UNIX systems - with this program leading the charge -
    don't rely on filename extentions to tell you the type of a file, but look
    at the file's actual contents. This is, of course, more reliable, but
    requires a bit of I/O.
  dev_url: https://github.com/file/file

extra:
  recipe-maintainers:
    - mrakitin
