{% set name = "file" %}
{% set version = "5.46" %}

package:
  name: file-split
  version: {{ version }}

source:
  url: ftp://ftp.astron.com/pub/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # The CMake project used for Windows assumes paths are ./file/src/
  folder: file  # [win]
  sha256: c9cc77c7c560c543135edc555af609d5619dbef011997e988ce40a3d75d86088
  patches:
    - patches/0001-Set-version-in-header.patch       # [win]
    - patches/0002-Add-Windows-header-imports.patch  # [win]

build:
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - gnuconfig  # [unix]
    - make       # [unix]
    - cmake      # [win]
    - ninja      # [win]
  host:
    - pcre2 {{ pcre2 }}   # [win]
    - xz {{ xz }}
    - zlib {{ zlib }}
    - zstd {{ zstd }}

outputs:
  - name: libmagic
    build:
      run_exports:
        - {{ pin_subpackage('libmagic', max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - gnuconfig  # [unix]
        - make       # [unix]
        - cmake      # [win]
        - ninja      # [win]
      host:
        - pcre2 {{ pcre2 }}   # [win]
        - xz {{ xz }}
        - zlib {{ zlib }}
        - zstd {{ zstd }}
    files:
      - include/magic.h            # [unix]
      - lib/libmagic.*             # [unix]
      - share/misc/magic.mgc       # [unix]
      - lib/pkgconfig/libmagic.pc  # [unix]
      - Library/include/magic.h            # [win]
      - Library/bin/libmagic.*             # [win]
      - Library/lib/libmagic.*             # [win]
      - Library/share/misc/magic.mgc       # [win]
      - Library/lib/pkgconfig/libmagic.pc  # [win]
    test:
      commands:
        - "test -r $CONDA_PREFIX/lib/libmagic${SHLIB_EXT}"  # [unix]
        - "if not exist %LIBRARY_BIN%/libmagic.dll exit 1"  # [win]
        - "if not exist %LIBRARY_LIB%/libmagic.lib exit 2"  # [win]
    about:
      summary: Implementation of the file(1) command

  - name: file
    requirements:
      build:
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - make  # [unix]
      host:
        # Not needed since no build will happen, but it stop conda-build from complaining
        # that libmagic doesn't exist during the DSO analysis.
        - {{ pin_subpackage("libmagic", exact=True) }}
      run:
        - {{ pin_subpackage("libmagic", exact=True) }}
    files:
      - bin/file                  # [unix]
      - share/man/man*/file*      # [unix]
      - share/man/man*/magic*     # [unix]
      - share/man/man*/libmagic*  # [unix]
      - Library/bin/file.exe              # [win]
      - Library/share/man/man*/file*      # [win]
      - Library/share/man/man*/magic*     # [win]
      - Library/share/man/man*/libmagic*  # [win]
    test:
      commands:
        - file -v
        - file --version  # same as above
        - file --help
    about:
      summary: Fine Free File Command
      description: |
        The file command is "a file type guesser", that is, a command-line tool
        that tells you in words what kind of data a file contains. Unlike most GUI
        systems, command-line UNIX systems - with this program leading the charge -
        don't rely on filename extentions to tell you the type of a file, but look
        at the file's actual contents. This is, of course, more reliable, but
        requires a bit of I/O.

about:
  home: https://darwinsys.com/file/
  summary: Fine Free File Command
  description: |
    The file command is "a file type guesser", that is, a command-line tool that tells you in words what kind of data
    a file contains.
  license: BSD-2-Clause-Darwin
  license_family: BSD
  license_file: COPYING
  dev_url: https://github.com/file/file
  doc_url: https://darwinsys.com/file/

extra:
  skip-lints:
    - incorrect_license
    - invalid_url
  recipe-maintainers:
    - chrisburr
    - mariusvniekerk
    - mrakitin
