{% set name = "file" %}
{% set version = "5.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ftp://ftp.astron.com/pub/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f05d286a76d9556243d0cb05814929c2ecf3a5ba07963f8f70bfaaa70517fad1

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - zlib  # [unix]

outputs:
  - name: libmagic
    requirements:
      build:
        - {{ compiler('c') }}
        - make
      host:
        - zlib  # [unix]
    files:
      - include/
      - lib/
      - share/misc/
    test:
      commands:
        - "test -r $CONDA_PREFIX/lib/libmagic${SHLIB_EXT}"
    about:
      summary: Implementation of the file(1) command

  - name: file
    requirements:
      build:
        - {{ compiler('c') }}
        - make
      host:
        - zlib  # [unix]
      run:
        - {{ pin_compatible("libmagic", max_pin="x.x.x.x.x.x.x.x.x") }}
    files:
      - bin/
      - share/man/
    test:
      commands:
        - file -v
        - file --version  # same as above
        - file --help
    about:
      summary: Fine Free File Command
      description: |
        The file command is "a file type guesser", that is, a command-line tool
        that tells you in words what kind of data a file contains. Unlike most GUI
        systems, command-line UNIX systems - with this program leading the charge -
        don't rely on filename extentions to tell you the type of a file, but look
        at the file's actual contents. This is, of course, more reliable, but
        requires a bit of I/O.

about:
  home: http://darwinsys.com/file
  summary: Fine Free File Command
  license: BSD-2-Clause
  license_file: COPYING
  dev_url: https://github.com/file/file

extra:
  recipe-maintainers:
    - mrakitin
